name: Norns CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  linux-build:
    name: Linux Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]
        platform: [DESKTOP]
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build and test in Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .github/workflows/linux-build.Dockerfile
          push: false
          load: true
          tags: norns-build:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            BUILD_TYPE=${{ matrix.build-type }}
            PLATFORM=${{ matrix.platform }}
      
      - name: Run tests in Docker
        run: |
          docker run --rm norns-build:latest /bin/bash -c "cd /norns && ./build.sh test --platform=${{ matrix.platform }} --type=${{ matrix.build-type }}"
      
      # Temp fix for https://github.com/actions/cache/issues/810
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  macos-build:
    name: macOS Build & Test
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install dependencies
        run: |
          brew update
          brew install cmake
          brew install pkg-config
          brew install lua@5.3
          brew install liblo
          brew install jack
          brew install sdl2
          brew install libsndfile
          brew install faust
          brew install luarocks
          luarocks install ldoc
      
      - name: Configure
        run: |
          ./build.sh configure --desktop --type=Debug
      
      - name: Build
        run: |
          ./build.sh build
      
      - name: Test
        run: |
          ./build.sh test

  raspberry-pi-build:
    name: Raspberry Pi Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-pi-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-pi-
      
      - name: Build for Raspberry Pi in Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .github/workflows/pi-build.Dockerfile
          push: false
          load: true
          tags: norns-pi-build:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      
      - name: Run cross-compilation
        run: |
          docker run --rm norns-pi-build:latest /bin/bash -c "cd /norns && ./build.sh build --platform=PI3 --type=Release"
      
      # Temp fix for https://github.com/actions/cache/issues/810
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  documentation:
    name: Generate Documentation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hererocks
          hererocks lua_install -r^ --lua=5.3
          export PATH=$PATH:$PWD/lua_install/bin
          luarocks install ldoc
      
      - name: Generate documentation
        run: |
          cd lua
          ldoc -d ../doc/docs/norns/api -c ../config.ld .
      
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
          keep_files: true
